class MyException(Exception):
    pass

raise MyException('My test exception')
